version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/vscode-salt"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10