name: Rust FMT

on:
  pull_request:
    branches: [ master ]
env:
  CARGO_TERM_COLOR: always
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update && sudo apt-get install gcc clang g++ -y
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check --